packages:
  - 'apps/*'
  - 'packages/*'


catalog:
  autoprefixer: 10.4.21
  classnames: 2.3.2
  esbuild: 0.25.8
  eslint: 9.32.0
  eslint-plugin-react: 7.37.5
  eslint-plugin-jsx-a11y: 6.10.2
  eslint-plugin-react-hooks: 5.2.0
  eslint-plugin-react-refresh: 0.4.20
  eslint-plugin-storybook: 9.1.1
  date-fns: 4.1.0
  globals: 16.3.0
  json-schema-to-zod: 2.6.1
  lucide-react: 0.536.0
  postcss: 8.5.6
  postcss-cli: 11.0.1
  postcss-combine-duplicated-selectors: 10.0.3
  postcss-custom-media: 11.0.6
  postcss-discard-empty: 7.0.1
  postcss-import: 16.1.1
  postcss-nesting: 13.0.2
  react: 19.1.1
  react-dom: 19.1.1
  react-remove-scroll-bar: 2.3.8
  react-error-boundary: 6.0.0
  rollup-plugin-visualizer: 5.14.0
  semver: 7.7.2
  storybook: 9.1.1
  stylelint: 16.23.0
  tailwindcss: 3.4.17
  tailwindcss-animate: 1.0.7
  tailwind-merge: 3.3.1
  typescript: 5.9.2
  typescript-eslint: 8.39.0
  vite: 7.0.6
  vitest: 3.2.4
  vite-tsconfig-paths: 5.1.4
  vite-plugin-top-level-await: 1.6.0
  vite-plugin-bundlesize: 0.2.0
  zod: 4.0.15
  "@eslint/js": 9.32.0
  "@incmix/utils": 0.36.3
  "@julr/vite-plugin-validate-env": 2.2.0
  "@radix-ui/colors": 3.0.0
  "@radix-ui/react-accessible-icon": 1.1.7
  "@radix-ui/react-alert-dialog": 1.1.14
  "@radix-ui/react-aspect-ratio": 1.1.7
  "@radix-ui/react-avatar": 1.1.10
  "@radix-ui/react-checkbox": 1.3.2
  "@radix-ui/react-collection": 1.1.7
  "@radix-ui/react-compose-refs": 1.1.2
  "@radix-ui/react-context": 1.1.2
  "@radix-ui/react-context-menu": 2.2.15
  "@radix-ui/react-dialog": 1.1.14
  "@radix-ui/react-direction": 1.1.1
  "@radix-ui/react-dropdown-menu": 2.1.15
  "@radix-ui/react-hover-card": 1.1.14
  "@radix-ui/react-navigation-menu": 1.2.13
  "@radix-ui/react-popover": 1.1.14
  "@radix-ui/react-portal": 1.1.9
  "@radix-ui/react-primitive": 2.1.3
  "@radix-ui/react-progress": 1.1.7
  "@radix-ui/react-radio-group": 1.3.7
  "@radix-ui/react-roving-focus": 1.1.10
  "@radix-ui/react-scroll-area": 1.2.9
  "@radix-ui/react-select": 2.2.5
  "@radix-ui/react-slider": 1.3.5
  "@radix-ui/react-slot": 1.2.3
  "@radix-ui/react-switch": 1.2.5
  "@radix-ui/react-tabs": 1.1.12
  "@radix-ui/react-toggle-group": 1.1.10
  "@radix-ui/react-tooltip": 1.2.7
  "@radix-ui/react-use-controllable-state": 1.2.2
  "@radix-ui/react-visually-hidden": 1.2.3
  "@storybook/addon-docs": 9.1.0
  "@storybook/addon-onboarding": 9.1.0
  "@storybook/react-vite": 9.1.0
  "@types/node": 24.1.0
  "@tailwindcss/typography": 0.5.16
  "@tailwindcss/vite": 4.1.11
  "@tanstack/zod-form-adapter": 0.42.1
  "@tanstack/react-form": 1.18.0
  "@tanstack/react-query": 5.81.5
  "@tanstack/react-router": 1.130.12
  "@tanstack/react-table": 8.21.3
  "@tanstack/router-cli": 1.130.15
  "@tanstack/router-devtools": 1.130.13
  "@types/react": 19.1.9
  "@types/react-dom": 19.1.7
  "@typescript-eslint/utils": 8.39.0
  "@vitejs/plugin-react": 4.7.0
  "@vitejs/plugin-react-swc": 3.11.0
  "@types/wicg-file-system-access": 2023.10.6