name: Publish to NPM

on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build package
        run: pnpm build
        working-directory: packages/ui-base

      - name: Run lint
        run: pnpm lint
        working-directory: packages/ui-base

      - name: Publish to NPM
        run: pnpm publish --no-git-checks
        working-directory: packages/ui-base
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}